"use client"
import ScrollProvider from '@/contexts/ScrollContext'
import './globals.css'
import { Inter } from 'next/font/google'
import NavBar from '@/components/NavBar/NavBar'
import Footer from '@/components/App/Footer'
import ScreenProvider from '@/contexts/ScreenContext'
import ThemeProvider from '@/contexts/ThemeContext'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({ children }) {


    return (
        <html lang="en">
            <body className={inter.className}>
                <ThemeProvider>
                    <ScrollProvider>
                        <ScreenProvider>
                            <NavBar />
                            <div className="w-full bg-inherit flex justify-center">
                                {children}
                            </div>
                            <Footer />
                        </ScreenProvider>
                    </ScrollProvider>
                </ThemeProvider>
            </body>
        </html>
    )
}
