import ScrollProvider from '@/contexts/ScrollContext'
import './globals.css'
import { Inter } from 'next/font/google'
import NavBar from '@/components/NavBar/NavBar'
import Footer from '@/components/App/Footer'
import ScreenProvider from '@/contexts/ScreenContext'
import ThemeProvider from '@/contexts/ThemeContext'
import AuthProvider from '@/contexts/AuthContext'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
    title: 'House Rental',
    description: 'Generated by create next app',
}

export default function RootLayout({ children }) {


    return (
        <html lang="en">
            <body className={inter.className}>
                <ThemeProvider>
                    <ScrollProvider>
                        <ScreenProvider>
                            <AuthProvider>
                                <NavBar />
                                <div className="w-full bg-inherit flex justify-center">
                                    {children}
                                </div>
                                <Footer />
                            </AuthProvider>
                        </ScreenProvider>
                    </ScrollProvider>
                </ThemeProvider>
            </body>
        </html>
    )
}
